- name: configuration play
  hosts: all
  gather_facts: no
  tasks:
    - name: backup current configuration
      cisco.ios.ios_command:
        commands:
          - show version
          - show running-config
          - show startup-config
      register: output
    - name: save output
      copy:
        content: "{{ output.stdout | join('\n') }}"
        dest: "../files/backup/backup_{{ inventory_hostname }}_{{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }}.txt"
      delegate_to: localhost
    - name: config interfaces
      cisco.ios.ios_interfaces:
        config: "{{ interfaces }}"
        state: merged
    - name: config L3 interfaces
      cisco.ios.ios_l3_interfaces:
        config: "{{ L3_interfaces }}"
        state: merged
    - name: config DHCP on R1 router
      cisco.ios.ios_config:
        src: "../templates/dhcp.j2"
      when: inventory_hostname == "R1"
    - name: Apply OSPFv2
      cisco.ios.ios_ospfv2:
        config: "{{ ospf }}"
        state: merged
      when: inventory_hostname in groups['routers']
    - name: config OSPF interfaces password
      cisco.ios.ios_config:
        src: "../templates/ospf_interfaces.j2"
      when: inventory_hostname in groups['routers']

