- name: check ospf
  gather_facts: no
  hosts: routers
  tasks:
    - name: show ip ospf neighbor
      ios_command:
        commands:
          - show ip ospf neighbor
      register: output

    - name: print result
      debug:
        msg: "The list of neighbor routers iD is {{ output.stdout[0] | return_router_ids }}"
