- name: check ospf
  gather_facts: no
  hosts: routers
  vars:
    routers_ids:
      - 1.1.1.1
      - 2.2.2.2
      - 3.3.3.3
      - 4.4.4.4
  tasks:
    - name: show ip OSPF neighbor
      ios_command:
        commands:
          - show ip OSPF neighbor
      register: output

    - name: print result
      debug:
        msg: "OSPF contains an intruder"
      when: output.stdout[0] | if_contain_intruders

    - name: get list of intruders
      set_fact:
        intruders_list: "{{ output.stdout[0].split('\n') }}"

    - name: print result 2
      debug:
        msg: "{{intruders_list}}"