interfaces:
  - name: e0/0
    description: mgmt_interface
    enabled: true
  - name: e0/1
    description: OSPF_links
    enabled: true
  - name: e0/2
    description: to_r1
    enabled: true
  - name: e0/3
    description: to_r4
    enabled: true
  - name: e1/0
    description: LAN1
    enabled: true