interfaces:
  - name: e0/0
    description: mgmt_interface
    enabled: true
  - name: e0/1
    description: OSPF_links
    enabled: true
  - name: e0/2
    description: to_r3
    enabled: true
  - name: e0/3
    description: to_r2
    enabled: true
  - name: e1/0
    description: LAN2
    enabled: true

L3_interfaces:
  - name: e0/0
    ipv4:
      - address: 192.168.1.6/24
  - name: e0/1
    ipv4:
      - address: 192.168.0.4/24
  - name: e0/2
    ipv4:
      - address: 192.168.2.14/30
  - name: e0/3
    ipv4:
      - address: 192.168.2.10/30
  - name: e1/0
    ipv4:
      - address: 192.168.4.2/24
    helper_addresses:
      ipv4:
        - destination_ip: 192.168.1.1


ospf:
  processes:
    - process_id: 1
      router_id: 4.4.4.4
      network:
        - address: 192.168.1.0
          wildcard_bits: 0.0.0.255
          area: 0
        - address: 192.168.0.0
          wildcard_bits: 0.0.0.255
          area: 0
        - address: 192.168.2.12
          wildcard_bits: 0.0.0.3
          area: 0
        - address: 192.168.2.8
          wildcard_bits: 0.0.0.3
          area: 0
        - address: 192.168.4.0
          wildcard_bits: 0.0.0.255
          area: 0
      passive_interface:
        interface:
          name:
            - e0/0
            - e1/0
