interfaces:
  - name: vlan 1
    description: mgmt_interface
    enable: true
  - name: e0/1
    description: to_r2
    enable: true
  - name: e0/2
    description: to_r1
    enable: true
  - name: e0/3
    description: access
    enable: true
  - name: e1/0
    description: access
    enable: true